FROM maven:latest

WORKDIR /code

COPY . /code

RUN mvn clean install -DskipTests=true

EXPOSE 8080

CMD ["java", "-jar", "/code/target/java-dropwizard-flyway-starter-1.0-SNAPSHOT.jar","server","/code/config.yml"]

ARG DB_HOST
ARG DB_PASSWORD
ARG DB_USERNAME
ARG DB_NAME
ARG ADMIN_USERNAME
ARG ADMIN_PASSWORD

ENV DB_HOST ${DB_HOST}
ENV DB_PASSWORD ${DB_PASSWORD}
ENV DB_USERNAME ${DB_USERNAME}
ENV DB_NAME ${DB_NAME}
ENV ADMIN_USERNAME ${ADMIN_USERNAME}
ENV ADMIN_PASSWORD ${ADMIN_PASSWORD}
